[package]
name = "graftopstat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {version = "0.3.17", features = ["thread-pool"]}
tiny_http = "0.8.2"
async-std = "1.10.0"